apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-example-helm
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: 'https://github.com/argoproj/argocd-example-apps'
    path: helm-guestbook
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
#      parameters:
#        - name: image.tag
#          value: '0.2'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: guestbook
  project: default
  syncPolicy: {}



