apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-prerequisites
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: 'https://github.com/evtr/argocdlinkerd'
    path: guestbook/guestbook-prerequisites
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy: {}

