apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-simple
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: 'https://github.com/evtr/argocdlinkerd'
    path: guestbook/simple-redis
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: guestbook
  project: default
  syncPolicy: {}

