apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-simple
  namespace: guestbook
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: 'https://github.com/evtr/argocdlinkerd'
    path: guestbook/simple-redis
    targetRevision: HEAD
  destination:
    namespace: guestbook
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy: {}

