apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spire
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: 'https://github.com/spiffe/spire-tutorials'
    path: k8s
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: spire
  project: default
  syncPolicy: {}

