---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: emojivoto-web-ingress
  namespace: emojivoto
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: emojivoto.kitkube.dk
    http:
      paths:
      - backend:
          serviceName: web-svc
          servicePort: 80

